spring.application.name=practical-15-jwt
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/fsads52
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=Zm9yLXByYWN0aWNhbC0xNS1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy1ub3c=
jwt.expiration-ms=3600000
